apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-consumer-scaler
  namespace: dev
spec:
  scaleTargetRef:
    name: settlement-remuneration-unit-app
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 30
  cooldownPeriod: 120
  triggers:
  - type: kafka
    metadata:
      consumerGroup: settlement-remuneration-unit-consumer-group
      topic: keda-teste
      lagThreshold: "5"
      offsetResetPolicy: latest
      scaleToZeroOnInvalidOffset: "true"
      allowIdleConsumers: "true"
      excludePersistentLag: "false"
      sasl: scram_sha512
      tls: enable
    authenticationRef:
      name: kafka-trigger-auth
