apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- serviceaccount.yaml
- deployment.yaml
- deployment-pontual.yamls
- secret.yaml
- triggerauthentication.yaml
- keda-scaledobject.yaml
- keda-scaledobject-pontual.yaml
