apiVersion: v1
kind: Secret
metadata:
  name: kafka-config
  namespace: dev
  labels:
    app: settlement-remuneration-unit-app
    component: config
    confidentiality: confidential
  annotations:
    description: "Kafka connection configuration"
type: Opaque
data:
  kafka-brokers: |
    Yi0xLmthZmthLmdrNmNpNC5jMjAua2Fma2EudXMtZWFzdC0xLmFtYXpvbmF3cy5j
    b206OTA5NixiLTEua2Fma2EuZ2s2Y2k0LmMyMC5rYWZrYS51cy1lYXN0LTEuYW1h
    em9uYXdzLmNvbTo5MDk2
  kafka-topic: a2VkYS10ZXN0ZQ==
  kafka-consumer-group: a2VkYS1jb25zdW1lci1ncm91cA==
  kafka-username: a2Fma2E=
  kafka-password: T0Jyb2tlckVzdGFFbUNvbnN0YW50ZUV2b2x1Y2Fv
