apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: kafka-trigger-auth
  namespace: dev
spec:
  secretTargetRef:
  - parameter: username
    name: settlement-remuneration-unit-secret
    key: kafka-username
  - parameter: password
    name: settlement-remuneration-unit-secret
    key: kafka-password
  - parameter: brokers
    name: settlement-remuneration-unit-secret
    key: kafka-brokers
