apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-consumer-scaler
  namespace: dev
  labels:
    app: settlement-remuneration-unit-app
    workload-type: massivo
  annotations:
    description: "KEDA scaler for massive batch processing"
spec:
  scaleTargetRef:
    name: settlement-remuneration-unit-app
  minReplicaCount: 1 # Fixado em 1 réplica
  maxReplicaCount: 1 # Fixado em 1 réplica
  pollingInterval: 30 # Verifica a cada 30s
  cooldownPeriod: 120 # Desescala após 2 minutos
  fallback:
    failureThreshold: 5
    replicas: 1
  triggers:
  - type: kafka
    metadata:
      brokers: "placeholder" # Lido do TriggerAuthentication
      consumerGroup: settlement-remuneration-unit-consumer-group
      topic: settlement-remuneration-unit-kafka-local
      lagThreshold: "5" # Muito sensível - escala agressivamente
      offsetResetPolicy: latest
      scaleToZeroOnInvalidOffset: "false"
      allowIdleConsumers: "false"
      excludePersistentLag: "true"
      sasl: scram_sha512
      tls: enable
      version: "latest"
    authenticationRef:
      name: kafka-trigger-auth
