apiVersion: v1
kind: ServiceAccount
metadata:
  name: settlement-remuneration-unit-app
  namespace: dev
  labels:
    app: settlement-remuneration-unit-app
    component: consumer
    managed-by: keda
    owner: devops-team
automountServiceAccountToken: false
